@extends('layouts.app')
@section('title', 'Logicore - Think. Build. Scale.')
@section('meta_description', 'Logicore builds intelligent digital solutions and scalable systems that help businesses innovate, automate, and grow.')
@section('content')
    @include('sections.hero')
    @include('sections.about')
    @include('sections.services')
    @include('sections.team')
    @include('sections.portfolio')
    @include('sections.skills')
    @include('sections.testimonials')
    @include('sections.blog')
    @include('sections.contact')
@endsection
